version: "3"

x-basic-setting: &basic-setting
  init: true
  restart: unless-stopped
  logging:
    driver: json-file
    options:
      max-size: "2G"
      max-file: "2"
      compress: "true"
  healthcheck:
    test: [ "CMD-SHELL", "curl --fail http://localhost" ]
    interval: 30s
    timeout: 30s
    start_period: 10s
    retries: 3

networks:
  reverse_proxy:
    external: true
  pgsql:
    external: true

services:
  miniflux:
    <<: *basic-setting
    image: docker.io/miniflux/miniflux:2.0.31
    container_name: miniflux
    networks:
      - reverse_proxy
      - pgsql
    expose:
      - 8080
    environment:
      - DATABASE_URL=${ENV_DATABASE_URL}
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=${ENV_ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ENV_ADMIN_PASSWORD}
      - BASE_URL=${ENV_BASE_URL}
      - PROXY_IMAGES="all"
      - HTTP_CLIENT_USER_AGENT="Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0"
    healthcheck:
      test: [ "CMD", "/usr/bin/miniflux", "-healthcheck", "auto" ]
      interval: 30s
      timeout: 30s
      start_period: 10s
      retries: 3
